version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: web_server
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./index.html:/usr/share/nginx/index.html:ro
    networks:
      custom_net:
        ipv4_address: 10.10.10.2

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      custom_net:
        aliases:
          - new_db
          - dev_db
        ipv4_address: 10.10.10.3

volumes:
  pgdata:

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/28
